# Generated by Django 5.0.6 on 2024-07-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=100)),
                ("loan_type", models.CharField(max_length=100)),
                ("loan_amount", models.CharField(max_length=100)),
                ("interest_rate", models.CharField(max_length=100)),
                ("tenure", models.CharField(max_length=100)),
                ("processing_fee", models.CharField(max_length=100)),
            ],
        ),
    ]
