# Generated by Django 5.0.7 on 2024-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeLoanData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("interest_rate", models.CharField(max_length=255)),
                ("processing_fee", models.CharField(max_length=255)),
                ("loan_amount_tenure", models.CharField(max_length=255)),
            ],
        ),
    ]
