# Generated by Django 5.0.7 on 2024-07-19 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
