# Generated by Django 5.0.7 on 2024-07-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(max_length=50),
        ),
    ]
