# Generated by Django 5.0.7 on 2024-07-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_alter_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="password",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
