# Generated by Django 5.0.7 on 2024-07-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_profile_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="password",
        ),
    ]
